### ISSUE TITLE
Translation truncated below 1024 tokens

### ISSUE THREAD

**Issue by rahul08946** [winstxnhdw/nllb-api#190]
I am using the Self hosting option from your most recent version for the docker image with following config:
```
    image: 'ghcr.io/winstxnhdw/nllb-api:main'
    container_name: 'nllb'
    ports:
      - '7860:7860'
    environment:
      - APP_PORT=7860 
      - OMP_NUM_THREADS=4
      - WORKER_COUNT=2
      - CT2_USE_EXPERIMENTAL_PACKED_GEMM=1
      - CT2_FORCE_CPU_ISA=AVX2
```
Ive tested it and it works as expected but only generates a full response for inputs around 300 tokens or something near that.  
As far as Ive read, it should be able to handle text inputs up to 1024 tokens but the translated text is always incomplete, missing out on information or stops mid sentence. 

I have seen in the other issues that setting the MAX_INPUT_LENGTH env variable should help but should only be the case for more than 1024 tokens. Ive still tried it but with no difference in result. What am I missing?
